models:
  - name: fct_image_detections
    description: "Object detection results linked to Telegram messages"
    columns:
      - name: message_id
        description: "FK → fact_messages"
        tests:
          - not_null
          - relationships:
              to: ref('fact_messages')
              field: message_id
      - name: detected_object_class
        description: "Class name detected by YOLO"
        tests:
          - not_null
      - name: confidence_score
        description: "YOLO confidence score"
